version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    volumes:
      - .:/var/task
      - ~/.aws:/root/.aws
      - go:/go
      - node_modules:/var/task/node_modules

volumes:
  go:
  node_modules:
