version: '3'

tasks:
  test:
    cmds:
      - go test ./pkg/...

  clean:
    cmds:
      - rm -rf ./build/

  build:
    deps: [clean]
    env:
      GO111MODULE: on
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -ldflags="-s -w" -o build/updateDaily       ./pkg/handlers/daily
      - go build -ldflags="-s -w" -o build/updateDailyByTag  ./pkg/handlers/dailybytag
      - go build -ldflags="-s -w" -o build/updateWeekly      ./pkg/handlers/weekly
      - go build -ldflags="-s -w" -o build/updateWeeklyByTag ./pkg/handlers/weeklybytag

  diff:
    cmds:
      - yarn run serverless diff --stage dev

  deploy:
    deps: [build]
    cmds:
      - yarn run serverless deploy --verbose {{.CLI_ARGS}}
