version: '3'

tasks:
  test:
    cmds:
      - go test ./src/...

  clean:
    cmds:
      - rm -rf ./build/

  build:
    deps: [clean]
    env:
      GO111MODULE: on
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -ldflags="-s -w" -o build/updateDaily       ./pkg/handlers/daily
      - go build -ldflags="-s -w" -o build/updateDailyByTag  src/handlers/updateDailyByTag/main.go
      - go build -ldflags="-s -w" -o build/updateWeekly      src/handlers/updateWeekly/main.go
      - go build -ldflags="-s -w" -o build/updateWeeklyByTag src/handlers/updateWeeklyByTag/main.go

  diff:
    cmds:
      - yarn run serverless diff --stage dev

  deploy:
    deps: [build]
    cmds:
      - yarn run serverless deploy --verbose {{.CLI_ARGS}}
