version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  go: circleci/go@1.7.1
  node: circleci/node@5.0.2

executors:
  ubuntu:
    machine:
      image: ubuntu-2004:current

commands:
  setup-go:
    steps:
      - go/install:
          version: '1.15'
      - go/mod-download-cached

  setup-node:
    steps:
      - node/install:
          install-yarn: true
          node-version: '14'
      - node/install-packages:
          pkg-manager: yarn

  setup-aws:
    steps:
      - aws-cli/install
      - aws-cli/assume-role-with-web-identity:
          role-arn: ${AWS_IAM_ROLE_ARN}

  create-dotenv:
    steps:
      - run:
          name: create .env
          command: |
            echo "QIITA_ACCESS_TOKEN=${QIITA_ACCESS_TOKEN}" > .env

jobs:
  test:
    executor: ubuntu
    steps:
      - checkout
      - setup-go
      - run:
          name: go test
          command: ./bin/test
      - store_artifacts:
          path: cover.html

  deploy:
    executor: ubuntu
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - setup-aws
      - create-dotenv
      - setup-node
      - setup-go
      - run:
          name: deploy
          command: |
            yarn run deploy --stage << parameters.stage >>

workflows:
  build:
    jobs:
      - test

      - approval_deploy:
          type: approval
          requires: [test]

      - deploy:
          context: aws
          name: deploy_dev
          stage: dev
          requires: [approval_deploy]
          filters:
            branches:
              ignore: main

      - deploy:
          context: aws
          name: deploy_prod
          stage: prod
          requires: [approval_deploy]
          filters:
            branches:
              only: main
