version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.3
  go: circleci/go@1.7.1
  node: circleci/node@5.0.2

executors:
  ubuntu:
    machine:
      image: ubuntu-2004:current

commands:
  setup-go:
    steps:
      - go/install:
          version: '1.16'
      - go/mod-download-cached

  setup-go-task:
    steps:
      - run:
          name: install go-task
          command: go install github.com/go-task/task/v3/cmd/task@latest

  setup-node:
    steps:
      - node/install:
          install-yarn: true
          node-version: '14'
      - node/install-packages:
          pkg-manager: yarn

  setup-aws:
    steps:
      - aws-cli/install
      - aws-cli/assume-role-with-web-identity:
          role-arn: ${AWS_IAM_ROLE_ARN}

  create-dotenv:
    steps:
      - run:
          name: create .env
          command: |
            echo "QIITA_ACCESS_TOKEN=${QIITA_ACCESS_TOKEN}" > .env

jobs:
  build:
    executor: ubuntu
    steps:
      - checkout
      - setup-node
      - setup-go
      - setup-go-task
      - run:
          name: go test
          command: task test
      - run:
          name: build
          command: task build
      - run:
          name: sls package
          command: yarn run serverless package --stage prod

  deploy:
    executor: ubuntu
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - setup-aws
      - create-dotenv
      - setup-node
      - setup-go
      - setup-go-task
      - run:
          name: deploy
          command: task deploy -- --stage << parameters.stage >> --force

workflows:
  build:
    jobs:
      - build

      - approval_deploy:
          type: approval
          requires: [build]

      - deploy:
          context: aws
          name: deploy_dev
          stage: dev
          requires: [approval_deploy]
          filters:
            branches:
              ignore: main

      - deploy:
          context: aws
          name: deploy_prod
          stage: prod
          requires: [approval_deploy]
          filters:
            branches:
              only: main
