// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	entities "github.com/koki-develop/qiita-lgtm-ranking/src/entities"
	mock "github.com/stretchr/testify/mock"
)

// ItemsRepository is an autogenerated mock type for the ItemsRepository type
type ItemsRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: query
func (_m *ItemsRepository) FindAll(query string) (entities.Items, error) {
	ret := _m.Called(query)

	var r0 entities.Items
	if rf, ok := ret.Get(0).(func(string) entities.Items); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Items)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
