// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	entities "github.com/koki-develop/qiita-lgtm-ranking/src/entities"

	mock "github.com/stretchr/testify/mock"
)

// QiitaAPI is an autogenerated mock type for the QiitaAPI type
type QiitaAPI struct {
	mock.Mock
}

// GetItems provides a mock function with given fields: page, perPage, query
func (_m *QiitaAPI) GetItems(page int, perPage int, query string) (entities.Items, error) {
	ret := _m.Called(page, perPage, query)

	var r0 entities.Items
	if rf, ok := ret.Get(0).(func(int, int, string) entities.Items); ok {
		r0 = rf(page, perPage, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Items)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(page, perPage, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateItem provides a mock function with given fields: id, title, body, tags
func (_m *QiitaAPI) UpdateItem(id string, title string, body string, tags entities.Tags) error {
	ret := _m.Called(id, title, body, tags)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, entities.Tags) error); ok {
		r0 = rf(id, title, body, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
